[package]
name = "csv"
version = "1.4.0"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Fast CSV parsing with support for serde."
documentation = "https://docs.rs/csv"
homepage = "https://github.com/BurntSushi/rust-csv"
repository = "https://github.com/BurntSushi/rust-csv"
readme = "README.md"
keywords = ["csv", "comma", "parser", "delimited", "serde"]
license = "Unlicense/MIT"
categories = ["encoding", "parser-implementations"]
exclude = ["/.github", "/ci/*", "/scripts/*"]
edition = "2021"
rust-version = "1.95"

[workspace]
members = ["csv-core", "csv-index"]

[lib]
bench = false

[dependencies]
csv-core = { path = "csv-core", version = "0.1.11" }
fast-float2 = "0.2"
itoa = "1"
serde_core = "1.0"
simdutf8 = "0.1"
zmij = "1"

[dev-dependencies]
bstr = { version = "1", default-features = false, features = ["alloc", "serde"] }
criterion = { version = "0.5", default-features = false, features = ["cargo_bench_support"] }
serde = { version = "1.0", features = ["derive"] }

[[bench]]
name = "bench"
harness = false

[profile.release]
debug = true

[profile.bench]
debug = true

[features]
# when enabled, the compat flavor of simdutf8 will be used, which is a little slower
# but is a drop-in replacement for std::str::from_utf8, returning the position
# of the erroring field and the underlying error. (up to 16x faster than std::str::fromutf8)
# Otherwise, the basic flavor of simdutf8 will be used, which is faster but
# does not provide the position information. (up to 23x faster than std::str::fromutf8)
simd_utf8_compat = []
